	; Strings to accompany trinity.zap

	.GSTR STR?712,"                                     -- Walt Whitman"
	.GSTR STR?674,"                        -- Lewis Carroll"
	.GSTR STR?667,"                       -- Alexander Pope"
	.GSTR STR?708,"                    -- Emily Dickinson"
	.GSTR STR?664,"                    -- Henry David Thoreau"
	.GSTR STR?692,"                 -- Herman Melville"
	.GSTR STR?689,"                -- Nathaniel Hawthorne"
	.GSTR STR?697,"           -- Los Alamos ditty, circa 1945"
	.GSTR STR?661,"        -- David Byrne"
	.GSTR STR?700,"        -- Matthew 16:3 "
	.GSTR STR?679," -- Arthur C. Clarke"
	.GSTR STR?703," -- Arthur Rimbaud"
	.GSTR STR?684," -- P. David Lebling"
	.GSTR STR?669," a sun-dial, I suppose?"" said Alice,    "
	.GSTR STR?369," accomplish nothing"
	.GSTR STR?27," across the ground"
	.GSTR STR?521," admires the umbrella from all sides"
	.GSTR STR?680," Any sufficiently   "
	.GSTR STR?681," arcane magic is    "
	.GSTR STR?494," are watching every move you make"
	.GSTR STR?4," at the moment."
	.GSTR STR?476," avoids your touch with ease"
	.GSTR STR?373," be pointless"
	.GSTR STR?465," beats its wings"
	.GSTR STR?673," before it, and a long way behind it --"""
	.GSTR STR?457," blinks at you"
	.GSTR STR?486," blinks its eyes helplessly"
	.GSTR STR?643," blinks uncomprehendingly"
	.GSTR STR?424," bobs his head"
	.GSTR STR?551," buzzes"
	.GSTR STR?477," buzzes safely out of reach"
	.GSTR STR?394," call"
	.GSTR STR?698," Can ye not discern the "
	.GSTR STR?523," can't keep her eyes off the umbrella"
	.GSTR STR?2," changes your mind.
"
	.GSTR STR?549," chatters"
	.GSTR STR?496," chatters happily"
	.GSTR STR?552," chirps"
	.GSTR STR?556," clicks and hisses"
	.GSTR STR?548," crackles"
	.GSTR STR?555," crackles for a moment"
	.GSTR STR?464," cranes its neck"
	.GSTR STR?421," creeps "
	.GSTR STR?392," crie"
	.GSTR STR?445," croak"
	.GSTR STR?478," defies your hopeless attempt"
	.GSTR STR?475," deftly swerves away, then buzzes back for more"
	.GSTR STR?501," dives underwater, but soon reappears"
	.GSTR STR?6," divides the sky like a razor"
	.GSTR STR?146," Down"
	.GSTR STR?554," emits a burst of static"
	.GSTR STR?526," eyes the umbrella longingly"
	.GSTR STR?463," eyes you suspiciously"
	.GSTR STR?213," feel"
	.GSTR STR?534," flicks its tongue in and out"
	.GSTR STR?683," from technology.   "
	.GSTR STR?524," gazes at the umbrella, then at you"
	.GSTR STR?519," gazes lovingly at the umbrella"
	.GSTR STR?341," giggle"
	.GSTR STR?497," gives you a playful splash"
	.GSTR STR?492," glare at you with beady little eyes"
	.GSTR STR?645," grins at your funny words"
	.GSTR STR?600," growls in its throat"
	.GSTR STR?602," growls softly"
	.GSTR STR?339," grumble"
	.GSTR STR?370," have no desirable effect"
	.GSTR STR?546," hisses"
	.GSTR STR?535," hisses a threat"
	.GSTR STR?553," hisses quietly"
	.GSTR STR?393," holler"
	.GSTR STR?426," hums softly"
	.GSTR STR?26," if you did that.
"
	.GSTR STR?420," inches "
	.GSTR STR?682," indistinguishable  "
	.GSTR STR?343," intone"
	.GSTR STR?487," is running about underfoot"
	.GSTR STR?499," is watching you curiously"
	.GSTR STR?598," is watching you with interest"
	.GSTR STR?317," isn't likely"
	.GSTR STR?425," kicks his feet"
	.GSTR STR?595," licks a stream of drool off its chin"
	.GSTR STR?722," longs to respond, but can't"
	.GSTR STR?644," looks at you blankly"
	.GSTR STR?498," looks at you with bright, intelligent eyes"
	.GSTR STR?525," looks at you, then at the umbrella"
	.GSTR STR?458," makes a croaking sound"
	.GSTR STR?500," makes an odd whistling sound"
	.GSTR STR?422," moves slowly "
	.GSTR STR?433," moving "
	.GSTR STR?337," mutter"
	.GSTR STR?23," out of sight.
"
	.GSTR STR?432," pacing "
	.GSTR STR?427," race between your legs"
	.GSTR STR?550," rasps"
	.GSTR STR?533," rears its wedge-shaped head"
	.GSTR STR?336," remark"
	.GSTR STR?721," responds with a stream of chatter"
	.GSTR STR?599," rubs its eye, then turns to squint at you"
	.GSTR STR?461," ruffles its feathers"
	.GSTR STR?448," say"
	.GSTR STR?547," says"
	.GSTR STR?646," says something in Japanese"
	.GSTR STR?434," scrambling "
	.GSTR STR?462," scratches an itchy wing"
	.GSTR STR?606," scratches itself"
	.GSTR STR?431," scratching "
	.GSTR STR?447," screeche"
	.GSTR STR?485," scurries blindly around your feet"
	.GSTR STR?429," scurry over your feet"
	.GSTR STR?318," seems doubtful"
	.GSTR STR?319," seems unlikely"
	.GSTR STR?372," serve no purpose"
	.GSTR STR?493," sharpen their claws with anticipation"
	.GSTR STR?466," sharpens its beak"
	.GSTR STR?597," sharpens its claws on a rock"
	.GSTR STR?430," show no sign of stopping"
	.GSTR STR?342," sigh"
	.GSTR STR?699," signs of the times?    "
	.GSTR STR?212," smell"
	.GSTR STR?491," snap their claws at you"
	.GSTR STR?423," snaps his fingers"
	.GSTR STR?344," snicker"
	.GSTR STR?435," sniffing "
	.GSTR STR?338," snigger"
	.GSTR STR?605," snuffles"
	.GSTR STR?502," spins in crazy circles"
	.GSTR STR?446," squawk"
	.GSTR STR?495," stands on its tail"
	.GSTR STR?720," struggles to respond, but can only chatter"
	.GSTR STR?594," studies you with its red eye"
	.GSTR STR?670," surprised at her own ingenuity.        "
	.GSTR STR?428," swarm across the tundra"
	.GSTR STR?10," to the east"
	.GSTR STR?8," to the north"
	.GSTR STR?9," to the south"
	.GSTR STR?11," to the west"
	.GSTR STR?603," turns over"
	.GSTR STR?522," turns the umbrella over and over in her hands"
	.GSTR STR?520," twirls the umbrella and giggles"
	.GSTR STR?601," twitches"
	.GSTR STR?29," Up"
	.GSTR STR?604," whines gently"
	.GSTR STR?340," whisper"
	.GSTR STR?460," whistles"
	.GSTR STR?459," wiggles its head"
	.GSTR STR?395," yell"
	.GSTR STR?672," you know, because it goes a long way   "
	.GSTR STR?19,"
""Zero minus "
	.GSTR STR?352,""" isn't in the vocabulary that you can use."
	.GSTR STR?354,""" to complete this story."
	.GSTR STR?570,"""Able to Baker. We got a breeze blowin' right in our face! Is TR-4 sleepin' down there?""

""It's worse than that."""
	.GSTR STR?668,"""And 'the wabe' is the grass-plot round "
	.GSTR STR?577,"""Baker to Pittsburg. Did four-charlie get that radiosonde up yet?""

""Ah, negative, Baker. Will advise."""
	.GSTR STR?580,"""Can't we nix that?"" complains the talkie as romantic strings fade in and out."
	.GSTR STR?574,"""No luck on that radiosonde.""

The talkie clicks twice. ""Keep on it."""
	.GSTR STR?671,"""Of course it is. It's called 'wabe,'   "
	.GSTR STR?571,"""Oscillograph check,"" squeaks the talkie."
	.GSTR STR?565,"""Who's takin' care of the WACS in Fubar, Baker?"" (General laughter.)"
	.GSTR STR?51,"$VERIFY"
	.GSTR STR?25,", into the ranch.
"
	.GSTR STR?1,". A "
	.GSTR STR?28,". It looks as if "
	.GSTR STR?0,". The "
	.GSTR STR?20,".
"
	.GSTR STR?21,".

"
	.GSTR STR?356,"."""
	.GSTR STR?593,"[BUG!]"
	.GSTR STR?22,"]

"
	.GSTR STR?187,"5291-9481 nielK xileF"
	.GSTR STR?143,"a"
	.GSTR STR?302,"A bottle-nosed dolphin is playing just offshore."
	.GSTR STR?298,"A charming statue stands nearby."
	.GSTR STR?315,"A crudely drawn map hangs upon the wall."
	.GSTR STR?578,"A distorted waltz competes with the hissing of the talkie."
	.GSTR STR?90,"A forgotten woman, too aged to run, is sitting nearby."
	.GSTR STR?305,"A gigantic paper bird is perched nearby."
	.GSTR STR?301,"A gray fin is lurking just offshore."
	.GSTR STR?311,"A great, big German shepherd is curled up against the blockhouse."
	.GSTR STR?314,"A lantern is lying in the dirt at your feet."
	.GSTR STR?312,"A large map is hanging on the wall."
	.GSTR STR?629,"A lovely bit o' metal! And so useful. Hold onto it, ducky"
	.GSTR STR?582,"A lush string ensemble begin to swell above the talkie's hiss."
	.GSTR STR?306,"A paperback book is lying in the corner."
	.GSTR STR?313,"A printed notice is stuck into the grass."
	.GSTR STR?308,"A rattlesnake is coiled only a few feet away."
	.GSTR STR?258,"A ruby is lying at your feet."
	.GSTR STR?626,"A short walk east"
	.GSTR STR?300,"A skink is squinting at you from the shadows nearby."
	.GSTR STR?304,"A spade is leaning against the wall."
	.GSTR STR?271,"A sudden cliff blocks your path."
	.GSTR STR?316,"A thin man is standing just inside the bunker's entrance."
	.GSTR STR?529,"A twinkling aurora engulfs the paper bird"
	.GSTR STR?614,"Adeenatsat"
	.GSTR STR?402,"adjusts the ruby in its beak"
	.GSTR STR?676,"advanced technology "
	.GSTR STR?331,"affixed"
	.GSTR STR?639,"Ain't seen one like it in a long while"
	.GSTR STR?185,"Alice"
	.GSTR STR?24,"All at once "
	.GSTR STR?633,"All prams lead to Kensington Gardens, they say"
	.GSTR STR?7,"All prams lead to the Kensington Gardens."
	.GSTR STR?361,"amble "
	.GSTR STR?259,"An aged woman is selling crumbs nearby."
	.GSTR STR?299,"An arborvitae is cleaved by a silver axe."
	.GSTR STR?303,"An army of crabs is guarding the water's edge."
	.GSTR STR?297,"An old woman is standing under the tree."
	.GSTR STR?696,"And fired the flop heard 'round the world."
	.GSTR STR?666,"And now a bubble burst, and now a world."
	.GSTR STR?204,"any honey"
	.GSTR STR?675,"Any sufficiently    "
	.GSTR STR?41,"any verbs"
	.GSTR STR?178,"As you approach the notice"
	.GSTR STR?179,"As you bend to touch the grass"
	.GSTR STR?182,"As you stumble across the lawn"
	.GSTR STR?142,"As your feet touch the grass"
	.GSTR STR?40,"ask about"
	.GSTR STR?39,"ASK CHARACTER ABOUT"
	.GSTR STR?665,"Atoms or systems into ruin hurled,      "
	.GSTR STR?330,"attached"
	.GSTR STR?630,"'Ave ye ever seen such beauties? So loyal. And so, so hungry"
	.GSTR STR?114,"away"
	.GSTR STR?651,"babbling "
	.GSTR STR?559,"Baker, get calibration on the horn"
	.GSTR STR?257,"bang"
	.GSTR STR?152,"Bang!"
	.GSTR STR?145,"Barrow wight"
	.GSTR STR?139,"be holding"
	.GSTR STR?49,"begin"
	.GSTR STR?111,"beginning to swell"
	.GSTR STR?170,"begins to vibrate again"
	.GSTR STR?381,"bewildered"
	.GSTR STR?135,"big."
	.GSTR STR?52,"Biting"
	.GSTR STR?272,"Black trees block your path."
	.GSTR STR?275,"Blasted trees block your path."
	.GSTR STR?441,"blinks at you"
	.GSTR STR?53,"Blowing"
	.GSTR STR?201,"Boing!"
	.GSTR STR?110,"Boom!"
	.GSTR STR?196,"boot"
	.GSTR STR?32,"bottom"
	.GSTR STR?100,"brighter."
	.GSTR STR?206,"Brilliant"
	.GSTR STR?511,"BUG!"
	.GSTR STR?468,"Buzzing angrily, the giant bee hovers close by"
	.GSTR STR?88,"Charming"
	.GSTR STR?611,"Chetirnatsat"
	.GSTR STR?621,"Chetirye"
	.GSTR STR?418,"chooses not to respond"
	.GSTR STR?54,"Cleaning"
	.GSTR STR?167,"clear off"
	.GSTR STR?105,"Click!"
	.GSTR STR?99,"click."
	.GSTR STR?138,"Click."
	.GSTR STR?231,"climb"
	.GSTR STR?64,"close"
	.GSTR STR?57,"closed"
	.GSTR STR?120,"clunk"
	.GSTR STR?413,"cocks its head intelligently"
	.GSTR STR?401,"cocks its head to watch you"
	.GSTR STR?382,"confused"
	.GSTR STR?509,"Continuity on gamma three"
	.GSTR STR?690,"Could annihilation occur in matter,"
	.GSTR STR?228,"could break the wires"
	.GSTR STR?193,"could budge the lid"
	.GSTR STR?227,"could cut the wire"
	.GSTR STR?65,"could help you do that"
	.GSTR STR?223,"could loosen the screws"
	.GSTR STR?252,"could repair the button"
	.GSTR STR?248,"could repair the walkie-talkie"
	.GSTR STR?442,"covers its face with its paws and trembles"
	.GSTR STR?262,"crack"
	.GSTR STR?194,"Crack!"
	.GSTR STR?119,"crack,"
	.GSTR STR?263,"crack."
	.GSTR STR?175,"Crash!"
	.GSTR STR?234,"creak"
	.GSTR STR?453,"Crescent moon"
	.GSTR STR?173,"crimson"
	.GSTR STR?203,"crunch,"
	.GSTR STR?108,"Crunch."
	.GSTR STR?144,"de"
	.GSTR STR?211,"dead"
	.GSTR STR?417,"decides to ignore you"
	.GSTR STR?233,"Desert Island Decameron."
	.GSTR STR?653,"DET"
	.GSTR STR?504,"Detonator check, go"
	.GSTR STR?709,"Distant and dead resuscitate,                       "
	.GSTR STR?583,"Distant announcers rasp beneath a wash of static."
	.GSTR STR?177,"Do Not Walk On The Grass"
	.GSTR STR?398,"dodges a startled nanny"
	.GSTR STR?416,"doesn't respond"
	.GSTR STR?217,"Don't be so sure"
	.GSTR STR?33,"door"
	.GSTR STR?36,"down"
	.GSTR STR?184,"Dr. Strangelove"
	.GSTR STR?613,"Dvenatsat"
	.GSTR STR?615,"Dyesiat"
	.GSTR STR?607,"Dyevianatsat"
	.GSTR STR?616,"Dyeviat"
	.GSTR STR?92,"east"
	.GSTR STR?516,"eight"
	.GSTR STR?543,"Eight"
	.GSTR STR?585,"eighteen"
	.GSTR STR?592,"eleven"
	.GSTR STR?406,"emits a brief squawk"
	.GSTR STR?443,"emits a squeak of terror"
	.GSTR STR?30,"empty"
	.GSTR STR?171,"empty out"
	.GSTR STR?50,"end"
	.GSTR STR?42,"enough nouns"
	.GSTR STR?561,"Excess velocity is two baker. Repeat, two baker"
	.GSTR STR?47,"Explorer."
	.GSTR STR?359,"extraordinary"
	.GSTR STR?569,"Faint strains of music swim in and out of static."
	.GSTR STR?335,"fall over the edge"
	.GSTR STR?652,"fat "
	.GSTR STR?388,"Feed the birds"
	.GSTR STR?385,"Feed the hungry birds"
	.GSTR STR?186,"Felix Klein 1849-1925"
	.GSTR STR?78,"Fiddling with"
	.GSTR STR?588,"fifteen"
	.GSTR STR?717,"fifth"
	.GSTR STR?158,"fifty"
	.GSTR STR?326,"firm"
	.GSTR STR?713,"first"
	.GSTR STR?112,"five"
	.GSTR STR?540,"Five"
	.GSTR STR?123,"flickers and goes out"
	.GSTR STR?162,"folded quite nicely, thank you"
	.GSTR STR?87,"Fool"
	.GSTR STR?624,"Football! Sorry, hon, I'm too old to play"
	.GSTR STR?572,"For a moment, the talkie's music is crystal clear. Then the strings break up into distortion."
	.GSTR STR?513,"four"
	.GSTR STR?539,"Four"
	.GSTR STR?589,"fourteen"
	.GSTR STR?716,"fourth"
	.GSTR STR?451,"Fresh whole lizard"
	.GSTR STR?678,"from magic.         "
	.GSTR STR?693,"From this crude lab that spawned a dud,   "
	.GSTR STR?650,"gawking "
	.GSTR STR?505,"Geo, sync at three, two, one, mark"
	.GSTR STR?245,"gesture"
	.GSTR STR?134,"get in"
	.GSTR STR?81,"get into"
	.GSTR STR?82,"get out of"
	.GSTR STR?640,"Ghastly, ain't he? Everyone laughs"
	.GSTR STR?528,"Ghostly light flickers around the paper bird"
	.GSTR STR?117,"GND"
	.GSTR STR?107,"Gnomon can tether time or tide"
	.GSTR STR?149,"Gnomon is an island"
	.GSTR STR?531,"gobbles down "
	.GSTR STR?348,"Good idea"
	.GSTR STR?221,"Got it"
	.GSTR STR?174,"green"
	.GSTR STR?109,"growing!"
	.GSTR STR?346,"Had me worried there"
	.GSTR STR?648,"haughty "
	.GSTR STR?332,"have a long way to fall"
	.GSTR STR?508,"H-E nominal"
	.GSTR STR?558,"H-E secured"
	.GSTR STR?198,"Heavy"
	.GSTR STR?324,"here"
	.GSTR STR?48,"Historian."
	.GSTR STR?410,"hop"
	.GSTR STR?728,"How Wabewalker enters the first of Seven Portals"
	.GSTR STR?635,"Humph!"" she sniffs. ""Never touch the stuff"
	.GSTR STR?632,"I ain't Harrod's, dearie. Thirty p"
	.GSTR STR?711,"I am the clock myself.                              "
	.GSTR STR?219,"I suppose that makes you Luke Halpin"
	.GSTR STR?150,"If you can't beat 'em, join 'em"
	.GSTR STR?701,"Il y a une horloge"
	.GSTR STR?328,"immovab"
	.GSTR STR?215,"Impressive"
	.GSTR STR?34,"in"
	.GSTR STR?729,"In which Wabewalker chances upon a Hovel"
	.GSTR STR?726,"In which Wabewalker meets a Keeper of Birds"
	.GSTR STR?148,"in, north or south"
	.GSTR STR?141,"Indeed"
	.GSTR STR?118,"INF"
	.GSTR STR?358,"interesting"
	.GSTR STR?18,"into the desert"
	.GSTR STR?399,"is eyeing you with interest"
	.GSTR STR?125,"is getting dimmer"
	.GSTR STR?677,"is indistinguishable"
	.GSTR STR?60,"is interested in selling anything"
	.GSTR STR?55,"is looking for a fight"
	.GSTR STR?124,"is quite dim now"
	.GSTR STR?456,"It go BOOM"
	.GSTR STR?625,"It's just east o' here"
	.GSTR STR?218,"It's not a fish"
	.GSTR STR?200,"It's your funeral"
	.GSTR STR?232,"Just stick around"
	.GSTR STR?63,"Kicking"
	.GSTR STR?452,"Killed in the light of a crescent moon"
	.GSTR STR?250,"left"
	.GSTR STR?191,"Let gnomon write my epitaph"
	.GSTR STR?414,"listens intently"
	.GSTR STR?656,"Little else but desert lies in that direction"
	.GSTR STR?623,"Lived 'ere all me life"
	.GSTR STR?695,"Lo, the embattled savants stood           "
	.GSTR STR?238,"locked"
	.GSTR STR?70,"locksmith"
	.GSTR STR?638,"Looks a bit crumpled to me"
	.GSTR STR?637,"Looks a bit ragged to me"
	.GSTR STR?405,"looks up at you inquisitively"
	.GSTR STR?390,"Lord, have mercy"
	.GSTR STR?261,"Lots"
	.GSTR STR?634,"Lots o' boys around here, dearie"
	.GSTR STR?628,"Lovely bread crumbs, only thirty p a bag"
	.GSTR STR?251,"Masochist"
	.GSTR STR?641,"Me?"" The woman laughs and gestures at the pigeons. ""Here's all there is to know about me"
	.GSTR STR?266,"Meet Fat Man"
	.GSTR STR?197,"melt"
	.GSTR STR?706,"Merry, and Nought, and gay, and numb -"
	.GSTR STR?449,"Milk and honey"
	.GSTR STR?450,"Milk and honey, fresh whole lizard"
	.GSTR STR?454,"Mix 'em with a pinch o' garlic"
	.GSTR STR?517,"nine"
	.GSTR STR?544,"Nine"
	.GSTR STR?584,"nineteen"
	.GSTR STR?220,"Nope. Wrong city"
	.GSTR STR?91,"north"
	.GSTR STR?94,"northeast"
	.GSTR STR?96,"northwest"
	.GSTR STR?241,"Not a good idea"
	.GSTR STR?688,"not care about his offspring.         "
	.GSTR STR?655,"Nothing but trackless desert lies that way"
	.GSTR STR?371,"n't be very productive"
	.GSTR STR?368,"n't do anything useful"
	.GSTR STR?415,"obviously understands you"
	.GSTR STR?686,"of the necessity of death. If a man   "
	.GSTR STR?727,"Of the Red Stone's theft by a Runner of Roads"
	.GSTR STR?225,"off"
	.GSTR STR?647,"offended "
	.GSTR STR?243,"offer"
	.GSTR STR?229,"Oh, great"
	.GSTR STR?137,"Okay, sicko"
	.GSTR STR?224,"on"
	.GSTR STR?164,"one"
	.GSTR STR?536,"One"
	.GSTR STR?104,"One more like that, and you've had it"
	.GSTR STR?17,"One of the shades "
	.GSTR STR?56,"open"
	.GSTR STR?35,"out"
	.GSTR STR?155,"pair of binoculars"
	.GSTR STR?506,"Patch to Alpha Echo Three Five"
	.GSTR STR?79,"Paying respect to"
	.GSTR STR?419,"pays you no heed"
	.GSTR STR?530,"pecks contentedly at "
	.GSTR STR?439,"peers around nervously"
	.GSTR STR?327,"permanent"
	.GSTR STR?383,"perplexed"
	.GSTR STR?575,"Persistent clicks modulate a passage of music."
	.GSTR STR?180,"Physical Energy."
	.GSTR STR?260,"Ping!"
	.GSTR STR?69,"Playing with"
	.GSTR STR?101,"Ploop!"
	.GSTR STR?106,"plop"
	.GSTR STR?333,"plummet to your death"
	.GSTR STR?724,"ponders "
	.GSTR STR?140,"pop"
	.GSTR STR?103,"Pop!"
	.GSTR STR?725,"pores "
	.GSTR STR?116,"POS"
	.GSTR STR?409,"prance"
	.GSTR STR?627,"Princess Louise carved it all herself, she did"
	.GSTR STR?72,"Pulling on"
	.GSTR STR?73,"Pushing around"
	.GSTR STR?210,"put down"
	.GSTR STR?380,"puzzled"
	.GSTR STR?723,"puzzles "
	.GSTR STR?620,"Pyat"
	.GSTR STR?129,"Pyatnatsat"
	.GSTR STR?247,"question"
	.GSTR STR?702,"qui ne sonne pas. "
	.GSTR STR?411,"race"
	.GSTR STR?397,"races between the wheels of a perambulator"
	.GSTR STR?192,"raise"
	.GSTR STR?195,"red"
	.GSTR STR?43,"RESTART"
	.GSTR STR?44,"RESTORE"
	.GSTR STR?154,"rifle"
	.GSTR STR?249,"right"
	.GSTR STR?285,"Rock walls block your path."
	.GSTR STR?557,"Roger. Displacement, report"
	.GSTR STR?510,"Roger. Signature established"
	.GSTR STR?596,"'s breathing echoes in the tunnel"
	.GSTR STR?322,"'s doubtful"
	.GSTR STR?321,"'s not likely"
	.GSTR STR?320,"'s unlikely"
	.GSTR STR?62,"salesperson"
	.GSTR STR?659,"Same as it ever was,  "
	.GSTR STR?660,"Same as it ever was.  "
	.GSTR STR?45,"SAVE"
	.GSTR STR?403,"scampers around your feet"
	.GSTR STR?408,"scoots between your legs"
	.GSTR STR?560,"SCR-299 checks, Able"
	.GSTR STR?404,"scratches impatiently on the ground"
	.GSTR STR?438,"scratches its ear"
	.GSTR STR?714,"second"
	.GSTR STR?329,"secure"
	.GSTR STR?507,"Seismographic, confirm"
	.GSTR STR?515,"seven"
	.GSTR STR?542,"Seven"
	.GSTR STR?586,"seventeen"
	.GSTR STR?719,"seventh"
	.GSTR STR?80,"Shaking"
	.GSTR STR?276,"Sheer cliff walls block your path."
	.GSTR STR?619,"Shest"
	.GSTR STR?126,"Shestdyesiat"
	.GSTR STR?610,"Shestnatsat"
	.GSTR STR?642,"Shh!"" The old woman shudders. ""Ye musn't speak o' such things"
	.GSTR STR?444,"shivers with fear"
	.GSTR STR?214,"Show-off"
	.GSTR STR?132,"Sicko"
	.GSTR STR?389,"Sirens! The sirens"
	.GSTR STR?514,"six"
	.GSTR STR?541,"Six"
	.GSTR STR?587,"sixteen"
	.GSTR STR?718,"sixth"
	.GSTR STR?345,"Smart move"
	.GSTR STR?226,"Snap!"
	.GSTR STR?121,"snap,"
	.GSTR STR?532,"snaps up "
	.GSTR STR?436,"sniffs the air inquisitively"
	.GSTR STR?133,"So educated"
	.GSTR STR?309,"Some careless technician has left a walkie-talkie lying in the dirt."
	.GSTR STR?307,"Somebody has left a nice pair of binoculars at the landing's edge."
	.GSTR STR?489,"Something in the crevice is moving around"
	.GSTR STR?482,"Something is scratching around in the darkness"
	.GSTR STR?127,"Sorokpyat"
	.GSTR STR?98,"south"
	.GSTR STR?95,"southeast"
	.GSTR STR?97,"southwest"
	.GSTR STR?360,"special"
	.GSTR STR?157,"Splash!"
	.GSTR STR?649,"starched "
	.GSTR STR?254,"start"
	.GSTR STR?283,"Steep mountains block your path."
	.GSTR STR?169,"stops vibrating"
	.GSTR STR?412,"strut"
	.GSTR STR?400,"struts around the top of the toadstool"
	.GSTR STR?66,"surgeon"
	.GSTR STR?269,"Swimming in the Round Pond is strictly forbidden."
	.GSTR STR?503,"Switch to one zero three"
	.GSTR STR?618,"Syem"
	.GSTR STR?609,"Syemnatsat"
	.GSTR STR?71,"take off"
	.GSTR STR?172,"take out"
	.GSTR STR?279,"Tall cattails block your path."
	.GSTR STR?518,"ten"
	.GSTR STR?545,"Ten"
	.GSTR STR?707,"Than this smart Misery.               "
	.GSTR STR?347,"Thanks"
	.GSTR STR?350,"Thanks again"
	.GSTR STR?378,"That would be pointless"
	.GSTR STR?156,"that?"
	.GSTR STR?379,"That's a pointless thing to do"
	.GSTR STR?374,"That's impossible"
	.GSTR STR?564,"That's procurement's problem, not mine"
	.GSTR STR?631,"That's yer change, ducky. Twenty p out of fifty"
	.GSTR STR?5,"The arrow on the ring is already pointing "
	.GSTR STR?473,"The bee zooms around your head, waiting for a chance to strike"
	.GSTR STR?474,"The bee's three-inch stinger is poised for a strike"
	.GSTR STR?563,"The CITs are sittin' pretty, Baker"
	.GSTR STR?274,"The cliff is much too steep to climb."
	.GSTR STR?364,"The desert streaks past"
	.GSTR STR?273,"The forest is too dense that way."
	.GSTR STR?469,"The giant bee maintains its orbit around your head"
	.GSTR STR?471,"The giant bee spit-polishes its stinger"
	.GSTR STR?168,"The Gnomon Conquest"
	.GSTR STR?83,"The Greatest Story Ever Told"
	.GSTR STR?365,"The ground blurs beneath your feet"
	.GSTR STR?222,"The Illustrated Story of the Atom Bomb."
	.GSTR STR?12,"The lemming "
	.GSTR STR?685,"The love of posterity is a consequence"
	.GSTR STR?280,"The misty waters block your path."
	.GSTR STR?284,"The mountains are much too steep to climb."
	.GSTR STR?189,"The New Testament"
	.GSTR STR?527,"The paper bird glows with an eerie violet radiance"
	.GSTR STR?581,"The phrase ""gas for the generator"" emerges from a background of hiss."
	.GSTR STR?13,"The roadrunner "
	.GSTR STR?480,"The skink in your pocket scratches restlessly"
	.GSTR STR?479,"The skink squirms in your pocket"
	.GSTR STR?165,"The sun is moving!"
	.GSTR STR?567,"The talkie buzzes. ""Baker, can you get medic on a secure line?"""
	.GSTR STR?573,"The talkie hisses; you make out the word ""condenser."""
	.GSTR STR?579,"The talkie makes a sound like indigestion."
	.GSTR STR?568,"The talkie mutters, ""It'll never work."""
	.GSTR STR?205,"The War of the Worlds"
	.GSTR STR?270,"The water isn't deep enough here."
	.GSTR STR?351,"The word """
	.GSTR STR?694,"Their necks to Truman's axe uncurled,     "
	.GSTR STR?455,"Then stand back! 'Cause it go BOOM"
	.GSTR STR?294,"There aren't any entrances here."
	.GSTR STR?292,"There's no entrance that way."
	.GSTR STR?267,"There's no need to trample on the flowers."
	.GSTR STR?377,"There's no point in doing that"
	.GSTR STR?654,"There's nothing but trackless desert in that direction"
	.GSTR STR?490,"There's something scratching around inside the crevice"
	.GSTR STR?662,"They are of sick and diseased imaginations"
	.GSTR STR?710,"They show me as the dial or move as the hands of me,"
	.GSTR STR?715,"third"
	.GSTR STR?590,"thirteen"
	.GSTR STR?387,"Thirty p"
	.GSTR STR?386,"Thirty p for the starving birds"
	.GSTR STR?384,"Thirty p! Thirty p a bag"
	.GSTR STR?264,"this"
	.GSTR STR?265,"This is no time for catching rays"
	.GSTR STR?355,"This story doesn't recognize the word """
	.GSTR STR?691,"this were the thing to do it.      "
	.GSTR STR?512,"three"
	.GSTR STR?538,"Three"
	.GSTR STR?122,"thump"
	.GSTR STR?190,"thunk."
	.GSTR STR?208,"Thunk."
	.GSTR STR?636,"Tidy bit o' foldin', that"
	.GSTR STR?658,"Time isn't after us.  "
	.GSTR STR?657,"Time isn't holding us."
	.GSTR STR?705,"To leave me in the Atom's Tomb -      "
	.GSTR STR?31,"top"
	.GSTR STR?46,"Tourist."
	.GSTR STR?75,"Toying in this way with"
	.GSTR STR?622,"Tree"
	.GSTR STR?612,"Treenatsat"
	.GSTR STR?128,"Treetsat"
	.GSTR STR?437,"trembles with agitation"
	.GSTR STR?37,"Trinity"
	.GSTR STR?89,"Trinity."
	.GSTR STR?363,"trudge "
	.GSTR STR?68,"Trying to destroy"
	.GSTR STR?334,"tumble to an early grave"
	.GSTR STR?85,"Turning"
	.GSTR STR?591,"twelve"
	.GSTR STR?159,"twenty"
	.GSTR STR?704,"'Twere better Charity                 "
	.GSTR STR?113,"two"
	.GSTR STR?537,"Two"
	.GSTR STR?181,"umbrella's handle"
	.GSTR STR?286,"Unassisted flight is not one of your talents."
	.GSTR STR?161,"unfold"
	.GSTR STR?163,"unfolded"
	.GSTR STR?357,"unusual"
	.GSTR STR?153,"up"
	.GSTR STR?147,"up, north or south"
	.GSTR STR?67,"veterinarian"
	.GSTR STR?246,"voice"
	.GSTR STR?617,"Vosyem"
	.GSTR STR?608,"Vosyemnatsat"
	.GSTR STR?731,"Wabewalker heeds the Magpie's words"
	.GSTR STR?730,"Wabewalker's encounter with a Magpie"
	.GSTR STR?362,"walk "
	.GSTR STR?77,"wants to play piggyback"
	.GSTR STR?440,"washes its face with its paws"
	.GSTR STR?407,"watches every move you make"
	.GSTR STR?562,"We got confirmation from Carrizozo"
	.GSTR STR?349,"Well done"
	.GSTR STR?687,"were sure of living forever, he would "
	.GSTR STR?93,"west"
	.GSTR STR?375,"What a ridiculous concept"
	.GSTR STR?391,"What to do, what to do"
	.GSTR STR?102,"Where gnomon has gone before"
	.GSTR STR?325,"where you are"
	.GSTR STR?323,"where you're standing"
	.GSTR STR?151,"Whew"
	.GSTR STR?663,"who would toll the world's knell so soon. "
	.GSTR STR?310,"Whoever was driving this jeep left it in an awful hurry. There's a wallet on the floor at your feet."
	.GSTR STR?86,"Whoosh!"
	.GSTR STR?470,"With an angry buzz, the giant bee streaks into view"
	.GSTR STR?59,"would accept your offer"
	.GSTR STR?237,"would affect the box"
	.GSTR STR?230,"would affect the cables"
	.GSTR STR?216,"would affect the coconut"
	.GSTR STR?188,"would affect the oak"
	.GSTR STR?209,"would affect the skink"
	.GSTR STR?58,"would agree with you"
	.GSTR STR?199,"would appeal to a lemming"
	.GSTR STR?76,"would appreciate your reading"
	.GSTR STR?160,"would be impressed by your offer"
	.GSTR STR?61,"would buy anything"
	.GSTR STR?207,"would do much damage"
	.GSTR STR?136,"would find that very appetizing"
	.GSTR STR?74,"would fit very well"
	.GSTR STR?84,"would go very far"
	.GSTR STR?202,"would have much effect"
	.GSTR STR?166,"would help you move the gnomon"
	.GSTR STR?239,"would lock the box"
	.GSTR STR?176,"would move the pram very far"
	.GSTR STR?235,"would open the box"
	.GSTR STR?240,"would open the padlock"
	.GSTR STR?130,"would react"
	.GSTR STR?38,"would respond"
	.GSTR STR?255,"would start the jeep"
	.GSTR STR?242,"would support your weight"
	.GSTR STR?236,"would unlock the box"
	.GSTR STR?131,"wrapped in the shroud"
	.GSTR STR?256,"you"
	.GSTR STR?244,"You asked for it"
	.GSTR STR?481,"You can feel the skink moving in your pocket"
	.GSTR STR?488,"You can hear something moving in the crevice"
	.GSTR STR?483,"You can hear something scrambling around your feet"
	.GSTR STR?282,"You can only go up or down from here."
	.GSTR STR?15,"You can't "
	.GSTR STR?376,"You can't be serious"
	.GSTR STR?290,"You can't move around like that in a jeep."
	.GSTR STR?3,"You don't "
	.GSTR STR?353,"You don't need to use the word """
	.GSTR STR?467,"You hear a familiar buzz nearby"
	.GSTR STR?576,"You hear a hearty guffaw on the talkie. ""Never get that one past CIC."""
	.GSTR STR?484,"You hear a scrambling noise underfoot"
	.GSTR STR?472,"You hear the bee circling above your head"
	.GSTR STR?295,"You hit your head against the side of the reservoir."
	.GSTR STR?14,"You see "
	.GSTR STR?366,"You streak across the desert"
	.GSTR STR?566,"You wince as the music's pitch wavers uncertainly."
	.GSTR STR?367,"You zoom over the landscape"
	.GSTR STR?281,"You'd tumble down the hill if you went that way."
	.GSTR STR?183,"Your paper bird didn't survive the crash very well. All that's left of it is a crumpled piece of paper."
	.GSTR STR?16,"You're already "
	.GSTR STR?268,"You're already as close as anyone wants to get to the Albert Memorial."
	.GSTR STR?296,"You're already at the bottom of the reservoir."
	.GSTR STR?277,"You're already at the bottom of the stairs."
	.GSTR STR?289,"You're already at the top of the ladder."
	.GSTR STR?278,"You're already at the top of the stairs."
	.GSTR STR?291,"You're already in the jeep as far as you can go."
	.GSTR STR?288,"You're already in the shelter as far as you can go."
	.GSTR STR?287,"You're going that way whether you like it or not."
	.GSTR STR?293,"You're in the closet as far as you can go."
	.GSTR STR?253,"Zap!"
	.GSTR STR?115,"zero"
	.GSTR STR?396,"zigzags through a group of tourists"
	.ENDI
